SELECT
    t.NAME AS team_name,
    sc.BUSINESS_FUNCTION,
    SUM(f.CREDITS) AS total_credits,
    SUM(CASE WHEN f.CALENDAR_DATE >= DATE_TRUNC('MONTH', DATEADD('MONTH', -1, CURRENT_DATE()))
                  AND f.CALENDAR_DATE < DATE_TRUNC('MONTH', CURRENT_DATE()) THEN f.CREDITS ELSE 0 END) AS credits_last_month,
    SUM(CASE WHEN f.CALENDAR_DATE >= DATE_TRUNC('MONTH', DATEADD('MONTH', -2, CURRENT_DATE()))
                  AND f.CALENDAR_DATE < DATE_TRUNC('MONTH', DATEADD('MONTH', -1, CURRENT_DATE())) THEN f.CREDITS ELSE 0 END) AS credits_2_months_ago
FROM MAKE_DATA.DWH.FCT_SCENARIO f
JOIN MAKE_DATA.DWH.DIM_TEAM t
    ON f.ORG_TEAM_ID = t.ORG_TEAM_ID
    AND t.IS_LAST_VERSION = 1
LEFT JOIN MAKE_DATA.DWH.DIM_SCENARIO_CATEGORIZATION sc
    ON f.ORG_SCN_ID = sc.ORG_SCN_ID
    AND sc.IS_LAST_VERSION = 1
WHERE f.ORG_ID = '{{119.Make_LifeCycles__r.records[1].imt_Make_OrgId__c}}'
GROUP BY t.NAME, sc.BUSINESS_FUNCTION
ORDER BY total_credits DESC;