SELECT
    f.ORG_ID,
    COALESCE(enr.ZOOMINFO_FIRST_NAME || ' ' || enr.ZOOMINFO_LAST_NAME, enr.EMAIL_ADDRESS) AS user_name,
    enr.EMAIL_ADDRESS AS email,
    bus.USER_ID,
    u.USER_JOB_ROLE,
    u.USER_AUTOMATION_EXPERIENCE,
    u.USER_SKILLSET,
    u.USER_GOAL,
    LISTAGG(DISTINCT t.NAME, ', ') WITHIN GROUP (ORDER BY t.NAME) AS teams,
    SUM(f.CREDITS) AS total_credits,
    SUM(CASE WHEN f.CALENDAR_DATE >= DATE_TRUNC('MONTH', DATEADD('MONTH', -1, CURRENT_DATE()))
                  AND f.CALENDAR_DATE < DATE_TRUNC('MONTH', CURRENT_DATE()) THEN f.CREDITS ELSE 0 END) AS credits_last_month,
    SUM(CASE WHEN f.CALENDAR_DATE >= DATE_TRUNC('MONTH', DATEADD('MONTH', -2, CURRENT_DATE()))
                  AND f.CALENDAR_DATE < DATE_TRUNC('MONTH', DATEADD('MONTH', -1, CURRENT_DATE())) THEN f.CREDITS ELSE 0 END) AS credits_2_months_ago,
    SUM(CASE WHEN f.CALENDAR_DATE >= DATE_TRUNC('MONTH', DATEADD('MONTH', -1, CURRENT_DATE()))
                  AND f.CALENDAR_DATE < DATE_TRUNC('MONTH', CURRENT_DATE()) THEN f.CREDITS ELSE 0 END)
    - SUM(CASE WHEN f.CALENDAR_DATE >= DATE_TRUNC('MONTH', DATEADD('MONTH', -2, CURRENT_DATE()))
                  AND f.CALENDAR_DATE < DATE_TRUNC('MONTH', DATEADD('MONTH', -1, CURRENT_DATE())) THEN f.CREDITS ELSE 0 END) AS month_over_month_change
FROM MAKE_DATA.DWH.FCT_SCENARIO f
JOIN MAKE_DATA.DWH.BRG_USER_SCENARIO bus
    ON f.ORG_SCN_ID = bus.ORG_SCN_ID
    AND bus.IS_LAST_VERSION = 1
JOIN MAKE_DATA.DWH.DIM_TEAM t
    ON f.ORG_TEAM_ID = t.ORG_TEAM_ID
    AND t.IS_LAST_VERSION = 1
LEFT JOIN MAKE_DATA.SERVING_GDPR.SRV_GDPR_ENRICHED_USER_DAY enr
    ON bus.USER_ID = enr.USER_ID
LEFT JOIN MAKE_DATA.DWH.DIM_USER u
    ON bus.USER_ID = u.USER_ID
    AND u.IS_LAST_VERSION = 1
WHERE f.ORG_ID = CONCAT('m_', '{{119.SalesforceBundle.Make_LifeCycles__r.records[].imt_Make_OrgId__c}}')
    AND enr.EMAIL_ADDRESS IS NOT NULL
    AND TRIM(enr.EMAIL_ADDRESS) != ''
    AND LOWER(TRIM(enr.EMAIL_ADDRESS)) != 'undefined'
GROUP BY f.ORG_ID, enr.ZOOMINFO_FIRST_NAME, enr.ZOOMINFO_LAST_NAME, enr.EMAIL_ADDRESS, bus.USER_ID, u.USER_JOB_ROLE, u.USER_AUTOMATION_EXPERIENCE, u.USER_SKILLSET, u.USER_GOAL
ORDER BY total_credits DESC;